Repository Finastra/finastra-design-system, pull requests merged in 2019-11, with the labels that each got.

#27 feat(repeater): added component
  .github/CODEOWNERS
  apps/angular-test-app/src/app/app-routing.module.ts
  apps/angular-test-app/src/app/app.component.html
  apps/angular-test-app/src/app/app.module.ts
  apps/angular-test-app/src/app/components/home/home.component.html
  apps/angular-test-app/src/app/components/repeater-demo/field-matcher/field-matcher.component.css
  apps/angular-test-app/src/app/components/repeater-demo/field-matcher/field-matcher.component.html
  apps/angular-test-app/src/app/components/repeater-demo/field-matcher/field-matcher.component.ts
  apps/angular-test-app/src/app/components/repeater-demo/repeater-card-advanced-example/repeater-card-advanced-example.component.html
  apps/angular-test-app/src/app/components/repeater-demo/repeater-card-advanced-example/repeater-card-advanced-example.component.scss
  apps/angular-test-app/src/app/components/repeater-demo/repeater-card-advanced-example/repeater-card-advanced-example.component.ts
  apps/angular-test-app/src/app/components/repeater-demo/repeater-card-chart-example/repeater-card-chart-example.component.html
  apps/angular-test-app/src/app/components/repeater-demo/repeater-card-chart-example/repeater-card-chart-example.component.scss
  apps/angular-test-app/src/app/components/repeater-demo/repeater-card-chart-example/repeater-card-chart-example.component.ts
  apps/angular-test-app/src/app/components/repeater-demo/repeater-card-example/_repeater-card-example.theme.scss
  apps/angular-test-app/src/app/components/repeater-demo/repeater-card-example/repeater-card-example.component.html
  apps/angular-test-app/src/app/components/repeater-demo/repeater-card-example/repeater-card-example.component.scss
  apps/angular-test-app/src/app/components/repeater-demo/repeater-card-example/repeater-card-example.component.ts
  apps/angular-test-app/src/app/components/repeater-demo/repeater-demo.component.html
  apps/angular-test-app/src/app/components/repeater-demo/repeater-demo.component.scss
  apps/angular-test-app/src/app/components/repeater-demo/repeater-demo.component.ts
  apps/angular-test-app/src/app/components/table-demo/table-demo.component.scss
  apps/angular-test-app/src/app/material.module.ts
  apps/angular-test-app/src/app/routes.ts
  apps/angular-test-app/src/assets/Financial_Market_Volatility.jpeg
  apps/angular-test-app/src/styles.scss
  libs/angular-components/repeater/ng-package.json
  libs/angular-components/repeater/package.json
  libs/angular-components/repeater/src/component-repeater/component-repeater.component.html
  libs/angular-components/repeater/src/component-repeater/component-repeater.component.scss
  libs/angular-components/repeater/src/component-repeater/component-repeater.component.spec.ts
  libs/angular-components/repeater/src/component-repeater/component-repeater.component.ts
  libs/angular-components/repeater/src/index.ts
  libs/angular-components/repeater/src/repeater.component.html
  libs/angular-components/repeater/src/repeater.component.scss
  libs/angular-components/repeater/src/repeater.component.spec.ts
  libs/angular-components/repeater/src/repeater.component.ts
  libs/angular-components/repeater/src/repeater.module.ts
  package-lock.json
  package.json
  tsconfig.json
Labels: component, demo, enhancement, unit-tests-required

#62 feat(global-search): add doc update and remove
  apps/angular-test-app/src/app/components/global-search-demo/global-search-demo.component.html
  apps/angular-test-app/src/app/components/global-search-demo/global-search-demo.component.ts
  libs/angular-components/global-search/src/components/global-search-overlay/global-search-overlay-config.ts
  libs/angular-components/global-search/src/components/global-search-overlay/global-search-overlay.component.ts
  libs/angular-components/global-search/src/global-search.component.ts
  libs/angular-components/global-search/src/services/global-search-overlay.service.ts
  libs/angular-components/global-search/src/services/global-search.service.ts
Labels: component, enhancement

#60 bugfix(repeater): fix issue when building for production
  apps/angular-test-app/src/app/components/repeater-demo/repeater-card-advanced-example/repeater-card-advanced-example.component.ts
  apps/angular-test-app/src/app/components/repeater-demo/repeater-card-chart-example/repeater-card-chart-example.component.ts
  apps/angular-test-app/src/app/components/repeater-demo/repeater-card-example/repeater-card-example.component.ts
  apps/angular-test-app/src/app/components/repeater-demo/repeater-demo.component.html
Labels: bug, component

#61 bugfix(filter-tree): fixed change detection on dataSource
  libs/angular-components/filter/filter-tree/src/filter-tree.component.ts
Labels: bug, component

#55 unit-tests(scroll-to-top): remove unnecessary parameter
  libs/angular-components/scroll-to-top/src/scroll-to-top.component.html
  libs/angular-components/scroll-to-top/src/scroll-to-top.component.spec.ts
  libs/angular-components/scroll-to-top/src/scroll-to-top.component.ts
Labels: enhancement, unit-tests

#63 bugfix(filter-tree): fixed tree-divider rendering condition
  libs/angular-components/filter/filter-tree/src/filter-tree.component.html
Labels: bug, component

#64 bugfix(repeater): add configuration
  .github/CODEOWNERS
  angular.json
  libs/angular-components/filter/filter-tags/src/filter-tags.component.spec.ts
  libs/angular-components/index.ts
  libs/angular-components/repeater/index.ts
  libs/angular-components/repeater/jest.config.js
  libs/angular-components/repeater/ng-package.json
  libs/angular-components/repeater/src/component-repeater/component-repeater.component.spec.ts
  libs/angular-components/repeater/src/index.ts
  libs/angular-components/repeater/src/repeater.component.spec.ts
  libs/angular-components/repeater/test-setup.ts
  libs/angular-components/repeater/tsconfig.json
  libs/angular-components/repeater/tsconfig.lib.json
  libs/angular-components/repeater/tsconfig.spec.json
  libs/angular-components/repeater/tslint.json
  nx.json
  package-lock.json
  package.json
Labels: bug, component, project-config

#59 feat(table): add input selection and docs
  apps/angular-test-app/src/app/components/table-demo/table-demo.component.html
  apps/angular-test-app/src/app/components/table-demo/table-demo.component.scss
  apps/angular-test-app/src/app/components/table-demo/table-demo.component.spec.ts
  apps/angular-test-app/src/app/components/table-demo/table-demo.component.ts
  libs/angular-components/table/src/table.component.html
  libs/angular-components/table/src/table.component.ts
  libs/angular-components/table/src/table.models.ts
Labels: component, documentation, enhancement

#65 feat(filters): improve + fix filters
  libs/angular-components/filter/filter-tags/src/_filter-tags.theme.scss
  libs/angular-components/filter/filter-tags/src/filter-tags.component.html
  libs/angular-components/filter/filter-tags/src/filter-tags.component.ts
  libs/angular-components/filter/filter-tree/src/filter-tree.component.html
  libs/angular-components/filter/filter-tree/src/filter-tree.component.scss
  libs/angular-components/filter/filter-tree/src/filter-tree.component.spec.ts
  libs/angular-components/filter/filter-tree/src/filter-tree.component.ts
Labels: component, enhancement

#66 feat(filters): further improvements
  libs/angular-components/core/index.ts
  libs/angular-components/core/src/filter/filter.models.spec.ts
  libs/angular-components/core/src/filter/filter.models.ts
  libs/angular-components/core/src/filter/index.ts
  libs/angular-components/filter/filter-tags/src/filter-tags.component.ts
  libs/angular-components/filter/filter-tree/src/filter-tree.component.html
  libs/angular-components/filter/filter-tree/src/filter-tree.component.scss
  libs/angular-components/filter/filter-tree/src/filter-tree.component.ts
Labels: bug, component

#67 feat(vector-map): component improvements
  apps/angular-test-app/src/app/components/vector-map-demo/vector-map-demo.component.html
  apps/angular-test-app/src/app/components/vector-map-demo/vector-map-demo.component.ts
  libs/angular-components/vector-map/src/vector-map.component.html
  libs/angular-components/vector-map/src/vector-map.component.spec.ts
  libs/angular-components/vector-map/src/vector-map.component.ts
  libs/angular-components/vector-map/src/vector-map.models.ts
Labels: component, enhancement

#73 fix(angular-components): add elasticlunr as an explicit dependency
  libs/angular-components/ng-package.json
  libs/angular-components/package.json
Labels: bug, component

#72 feature(repeater) Add default selected items
  apps/angular-test-app/src/app/components/repeater-demo/repeater-demo.component.html
  libs/angular-components/repeater/src/repeater.component.spec.ts
  libs/angular-components/repeater/src/repeater.component.ts
Labels: component, enhancement

#71 fix(theme): child with margin in breadcrumb element.
  package-lock.json
  themes/angular-theme/lib/breadcrumb/_breadcrumb-base.scss
Labels: bug, theme

#74 revert #73
  libs/angular-components/ng-package.json
  libs/angular-components/package.json
Labels: component

#76 fix(core): all exports need to be explicitly exported from lib entry file
  angular.json
  libs/angular-components/core/index.ts
  libs/angular-components/core/src/palette/index.ts
  tsconfig.json
Labels: bug, component

#78 fix(repeater): fix single selection #77
  libs/angular-components/repeater/src/repeater.component.ts
Labels: bug, component
