Repository Finastra/finastra-design-system, pull requests merged in 2019-12, with the labels that each got.

#75 feature(table): make table editable with new configurations
  apps/angular-test-app/src/app/components/table-demo/table-demo.component.html
  apps/angular-test-app/src/app/components/table-demo/table-demo.component.ts
  libs/angular-components/table/CHANGELOG.md
  libs/angular-components/table/src/table.component.html
  libs/angular-components/table/src/table.component.scss
  libs/angular-components/table/src/table.component.spec.ts
  libs/angular-components/table/src/table.component.ts
  libs/angular-components/table/src/table.module.ts
Labels: component, enhancement

#85 feat(filters): filter improvements
  apps/angular-test-app/src/app/components/filter-panel-demo/filter-panel-demo.component.ts
  libs/angular-components/filter/filter-tags/src/filter-tags.component.html
  libs/angular-components/filter/filter-tags/src/filter-tags.component.ts
  libs/angular-components/filter/filter-tree/src/filter-tree.component.html
  libs/angular-components/filter/filter-tree/src/filter-tree.component.scss
  libs/angular-components/filter/filter-tree/src/filter-tree.component.spec.ts
  libs/angular-components/filter/filter-tree/src/filter-tree.component.ts
Labels: component, enhancement

#87 fix(table): fix table selection checking method to deep check
  libs/angular-components/package.json
  libs/angular-components/table/CHANGELOG.md
  libs/angular-components/table/src/table.component.html
  libs/angular-components/table/src/table.component.ts
  libs/angular-components/table/src/table.models.ts
  package-lock.json
  package.json
Labels: bug, component

#91 feat(global-search): add responsiveness
  libs/angular-components/global-search/src/_global-search.theme.scss
  libs/angular-components/global-search/src/components/global-search-overlay/global-search-overlay.component.html
  libs/angular-components/global-search/src/global-search.component.scss
Labels: component, enhancement

#88 feat(wizard): new wizard component
  .github/CODEOWNERS
  angular.json
  apps/angular-test-app/src/app/app-routing.module.ts
  apps/angular-test-app/src/app/app.component.html
  apps/angular-test-app/src/app/components/wizard-demo/wizard-demo.component.html
  apps/angular-test-app/src/app/components/wizard-demo/wizard-demo.component.scss
  apps/angular-test-app/src/app/components/wizard-demo/wizard-demo.component.spec.ts
  apps/angular-test-app/src/app/components/wizard-demo/wizard-demo.component.ts
  apps/angular-test-app/src/app/routes.ts
  apps/angular-test-app/src/styles.scss
  libs/angular-components/index.ts
  libs/angular-components/popover/tsconfig.json
  libs/angular-components/vector-map/tsconfig.json
  libs/angular-components/wizard/index.ts
  libs/angular-components/wizard/jest.config.js
  libs/angular-components/wizard/ng-package.json
  libs/angular-components/wizard/package.json
  libs/angular-components/wizard/src/_wizard.theme.scss
  libs/angular-components/wizard/src/animations.ts
  libs/angular-components/wizard/src/services/button-hub.service.spec.ts
  libs/angular-components/wizard/src/services/button-hub.service.ts
  libs/angular-components/wizard/src/services/page-collection.service.spec.ts
  libs/angular-components/wizard/src/services/page-collection.service.ts
  libs/angular-components/wizard/src/services/wizard-navigation.service.spec.ts
  libs/angular-components/wizard/src/services/wizard-navigation.service.ts
  libs/angular-components/wizard/src/wizard-button/wizard-button.component.html
  libs/angular-components/wizard/src/wizard-button/wizard-button.component.spec.ts
  libs/angular-components/wizard/src/wizard-button/wizard-button.component.ts
  libs/angular-components/wizard/src/wizard-page/wizard-page-description.directive.ts
  libs/angular-components/wizard/src/wizard-page/wizard-page-title.directive.ts
  libs/angular-components/wizard/src/wizard-page/wizard-page.component.spec.ts
  libs/angular-components/wizard/src/wizard-page/wizard-page.component.ts
  libs/angular-components/wizard/src/wizard-title.component.ts
  libs/angular-components/wizard/src/wizard.component.html
  libs/angular-components/wizard/src/wizard.component.scss
  libs/angular-components/wizard/src/wizard.component.spec.ts
  libs/angular-components/wizard/src/wizard.component.ts
  libs/angular-components/wizard/src/wizard.module.spec.ts
  libs/angular-components/wizard/src/wizard.module.ts
  libs/angular-components/wizard/test-setup.ts
  libs/angular-components/wizard/tsconfig.json
  libs/angular-components/wizard/tsconfig.lib.json
  libs/angular-components/wizard/tsconfig.spec.json
  libs/angular-components/wizard/tslint.json
  nx.json
  tsconfig.json
  tslint.json
Labels: component, demo, e2e-tests-required
