Repository Finastra/finastra-design-system, pull requests merged in 2020-01, with the labels that each got.

#93 feat(table): custom cell template
  apps/angular-test-app/src/app/components/table-demo/table-demo.component.html
  apps/angular-test-app/src/app/components/table-demo/table-demo.component.ts
  libs/angular-components/table/src/table.component.html
  libs/angular-components/table/src/table.component.scss
  libs/angular-components/table/src/table.component.ts
  libs/angular-components/table/src/table.models.ts
  package-lock.json
  package.json
Labels: component, enhancement

#98 bugfix(table): fix table pagination when data is updated
  libs/angular-components/table/src/table.component.ts
Labels: bug, component

#96 feature(accessibility): accessibility improvements
  apps/angular-test-app/src/app/app.component.html
  apps/angular-test-app/src/app/components/home/home.component.html
  apps/angular-test-app/src/app/components/repeater-demo/repeater-card-example/repeater-card-example.component.html
  apps/angular-test-app/src/app/components/repeater-demo/repeater-demo.component.html
  libs/angular-components/filter/filter-tags/src/filter-tags.component.html
  libs/angular-components/scroll-to-top/src/scroll-to-top.component.html
  libs/angular-components/table/src/table.component.html
Labels: component, enhancement

#100 fix(table) fix set selectionKeys
  apps/angular-test-app/src/app/components/table-demo/table-demo.component.html
  apps/angular-test-app/src/app/components/table-demo/table-demo.component.scss
  apps/angular-test-app/src/app/components/table-demo/table-demo.component.spec.ts
  apps/angular-test-app/src/app/components/table-demo/table-demo.component.ts
  libs/angular-components/table/src/table.component.ts
Labels: bug, component

#102 feat(button-toggle): update button toggle to comply with design
  apps/angular-test-app/src/app/components/filter-panel-demo/filter-panel-demo.component.html
  apps/angular-test-app/src/app/components/filter-panel-demo/filter-panel-demo.component.scss
  themes/angular-theme/lib/button-toggle/_button-toggle-base.scss
  themes/angular-theme/lib/button-toggle/_button-toggle-theme.scss
Labels: enhancement, theme

#101 feature(project): add strict mode
  .prettierrc
  .vscode/launch.json
  apps/angular-test-app-e2e/src/integration/app.spec.ts
  apps/angular-test-app-e2e/src/support/app.po.ts
  apps/angular-test-app/src/app/app.component.ts
  apps/angular-test-app/src/app/components/filter-panel-demo/filter-panel-demo.component.ts
  apps/angular-test-app/src/app/components/global-search-demo/global-search-demo.component.ts
  apps/angular-test-app/src/app/components/repeater-demo/field-matcher/field-matcher.component.ts
  apps/angular-test-app/src/app/components/repeater-demo/repeater-card-chart-example/repeater-card-chart-example.component.ts
  apps/angular-test-app/src/app/components/repeater-demo/repeater-demo.component.ts
  apps/angular-test-app/src/app/components/table-demo/table-demo.component.ts
  libs/angular-components/core/src/palette/palette.module.ts
  libs/angular-components/core/src/palette/palette.service.ts
  libs/angular-components/filter/filter-tags/src/filter-tags.component.ts
  libs/angular-components/filter/filter-tags/src/filter-tags.module.ts
  libs/angular-components/filter/filter-tree/src/filter-tree.component.spec.ts
  libs/angular-components/filter/filter-tree/src/filter-tree.component.ts
  libs/angular-components/global-search/src/components/global-search-overlay/global-search-overlay.component.ts
  libs/angular-components/global-search/src/global-search.component.ts
  libs/angular-components/global-search/src/services/global-search-overlay.service.ts
  libs/angular-components/global-search/src/services/global-search.service.ts
  libs/angular-components/popover/src/popover.component.ts
  libs/angular-components/popover/src/popover.module.ts
  libs/angular-components/repeater/src/component-repeater/component-repeater.component.ts
  libs/angular-components/repeater/src/repeater.component.ts
  libs/angular-components/scroll-to-top/src/scroll-to-top.component.ts
  libs/angular-components/table/src/table.component.ts
  libs/angular-components/table/src/table.models.ts
  libs/angular-components/vector-map/src/vector-map.component.html
  libs/angular-components/vector-map/src/vector-map.component.spec.ts
  libs/angular-components/vector-map/src/vector-map.component.ts
  libs/angular-components/vector-map/test-setup.ts
  libs/angular-components/wizard/src/services/page-collection.service.ts
  libs/angular-components/wizard/src/services/wizard-navigation.service.ts
  libs/angular-components/wizard/src/wizard-button/wizard-button.component.ts
  libs/angular-components/wizard/src/wizard-page/wizard-page.component.ts
  libs/angular-components/wizard/src/wizard.component.ts
  package-lock.json
  package.json
  themes/angular-theme/lib/core/theming/_all-theme.scss
  themes/angular-theme/lib/slide-toggle/_slide-toggle-theme.scss
  tsconfig.json
  tslint.json
Labels: enhancement, project-config

#107 fix(vector-map): catch plotly update error
  libs/angular-components/vector-map/src/vector-map.component.ts
Labels: bug, component

#108 fix(theme): fix tags, popover and chips weight
  libs/angular-components/filter/filter-tags/src/filter-tags.component.scss
  libs/angular-components/popover/src/popover.component.html
  libs/angular-components/popover/src/popover.component.scss
  themes/angular-theme/lib/button-toggle/_button-toggle-base.scss
  themes/angular-theme/lib/chips/_chips-theme.scss
Labels: bug, theme

#109 fix(codeowner): fix filter codeowners
  .github/CODEOWNERS
Labels: bug, project-config

#112 feature(components): bundle _*.theme.scss files into the components package
  angular.json
  apps/angular-test-app/src/styles.scss
  libs/angular-components/core/ng-package.json
  libs/angular-components/filter/filter-tags/ng-package.json
  libs/angular-components/filter/filter-tags/src/filter-tags.component.scss
  libs/angular-components/filter/filter-tree/ng-package.json
  libs/angular-components/filter/filter-tree/src/filter-tree.component.scss
  libs/angular-components/global-search/ng-package.json
  libs/angular-components/global-search/src/_global-search.theme.scss
  libs/angular-components/ng-package.json
  libs/angular-components/popover/ng-package.json
  libs/angular-components/popover/src/popover.component.scss
  libs/angular-components/repeater/ng-package.json
  libs/angular-components/scroll-to-top/ng-package.json
  libs/angular-components/scroll-to-top/package.json
  libs/angular-components/table/ng-package.json
  libs/angular-components/vector-map/ng-package.json
  libs/angular-components/vector-map/src/vector-map.component.scss
  libs/angular-components/wizard/ng-package.json
  libs/angular-components/wizard/src/_wizard.theme.scss
  libs/angular-components/wizard/src/wizard.component.scss
  tools/devkit/builders.json
  tools/devkit/builders/components/components-builder.ts
  tools/devkit/builders/components/schema.json
  tools/devkit/builders/components/schema.ts
  tools/devkit/builders/theme/schema.json
  tools/schematics/angular-component/files/ng-package.json.template
Labels: component, enhancement, project-config, theme

#113 bugfix(filter-tree): rename filter tree theme file
  libs/angular-components/filter/filter-tree/src/_filter-tree.theme.scss
Labels: bug, component

#114 bugfix(project-config): use public npm
  package-lock.json
Labels: bug, project-config

#115 feature(project-config): add npmrc
  .npmrc
Labels: enhancement, project-config

#116 bugfix(vector-map): fix instantiation of views
  libs/angular-components/vector-map/src/vector-map.component.ts
Labels: bug, component

#120 fix(icon): gradient background removed for IE11
  themes/angular-theme/lib/button/_button-theme.scss
  themes/angular-theme/lib/icon/_icon-theme.scss
Labels: bug, theme

#119 feat(theme): postcss + autoprefix
  angular.json
  package-lock.json
  package.json
  themes/angular-theme/package-lock.json
  themes/angular-theme/package.json
  tools/devkit/builders/theme/theme-builder.ts
  tools/devkit/tsconfig.devkit.json
Labels: enhancement, theme

#121 fix(global-search): rename var so that it does not reassign angular flex breakpoints
  libs/angular-components/global-search/src/_global-search.theme.scss
Labels: bug, component

#117 fix(theme): fix minor issues with button-toggle
  apps/angular-test-app/src/app/components/filter-panel-demo/filter-panel-demo.component.html
  themes/angular-theme/lib/button-toggle/_button-toggle-theme.scss
Labels: bug, theme
