Repository Finastra/finastra-design-system, pull requests merged in 2020-05, with the labels that each got.

#198 bugfix(theme): dark mode tweaks
  libs/angular-components/filter/filter-group/src/_filter-group.theme.scss
  themes/angular-theme/lib/badge/_badge-base.scss
  themes/angular-theme/lib/button-toggle/_button-toggle-theme.scss
  themes/angular-theme/lib/expansion/_expansion-base.scss
Labels: bug, theme

#172 feat(menu): new entity menu component
  angular.json
  apps/angular-test-app/src/app/app.module.ts
  apps/angular-test-app/src/app/components/entity-menu-demo/entity-menu-demo.component.html
  apps/angular-test-app/src/app/components/entity-menu-demo/entity-menu-demo.component.scss
  apps/angular-test-app/src/app/components/entity-menu-demo/entity-menu-demo.component.ts
  apps/angular-test-app/src/app/nested-routes.ts
  libs/angular-components/entity-menu/README.md
  libs/angular-components/entity-menu/index.ts
  libs/angular-components/entity-menu/jest.config.js
  libs/angular-components/entity-menu/ng-package.json
  libs/angular-components/entity-menu/package.json
  libs/angular-components/entity-menu/src/_entity-menu.theme.scss
  libs/angular-components/entity-menu/src/entity-menu.component.html
  libs/angular-components/entity-menu/src/entity-menu.component.scss
  libs/angular-components/entity-menu/src/entity-menu.component.spec.ts
  libs/angular-components/entity-menu/src/entity-menu.component.ts
  libs/angular-components/entity-menu/src/entity-menu.module.spec.ts
  libs/angular-components/entity-menu/src/entity-menu.module.ts
  libs/angular-components/entity-menu/test-setup.ts
  libs/angular-components/entity-menu/tsconfig.json
  libs/angular-components/entity-menu/tsconfig.lib.json
  libs/angular-components/entity-menu/tsconfig.spec.json
  libs/angular-components/entity-menu/tslint.json
  nx.json
  tsconfig.json
Labels: component, unit-tests-required

#182 bugfix(inputs): fix select
  apps/angular-test-app/src/app/components/ui-elements-demo/ui-elements-demo.component.html
  apps/angular-test-app/src/app/components/ui-elements-demo/ui-elements-demo.component.scss
  package-lock.json
  themes/angular-theme/lib/core/_core.scss
  themes/angular-theme/lib/select/_select-base.scss
Labels: bug, theme

#213 feature(user-profile-menu): Added MatMenuTrigger
  apps/angular-test-app/src/app/components/user-profile-menu-demo/user-profile-menu-demo-component.component.html
  libs/angular-components/user-profile-menu/src/user-profile-menu.component.html
  libs/angular-components/user-profile-menu/src/user-profile-menu.component.ts
  libs/angular-components/user-profile-menu/src/user-profile-panel.component.html
  libs/angular-components/user-profile-menu/src/user-profile-panel.component.ts
Labels: component, enhancement

#194 Account card component
  angular.json
  apps/angular-test-app/src/app/app.module.ts
  apps/angular-test-app/src/app/components/account-card-demo/account-card-demo.component.html
  apps/angular-test-app/src/app/components/account-card-demo/account-card-demo.component.scss
  apps/angular-test-app/src/app/components/account-card-demo/account-card-demo.component.ts
  apps/angular-test-app/src/app/nested-routes.ts
  libs/angular-components/cards/account-card/README.md
  libs/angular-components/cards/account-card/index.ts
  libs/angular-components/cards/account-card/jest.config.js
  libs/angular-components/cards/account-card/ng-package.json
  libs/angular-components/cards/account-card/package.json
  libs/angular-components/cards/account-card/src/_account-card.theme.scss
  libs/angular-components/cards/account-card/src/account-card.component.html
  libs/angular-components/cards/account-card/src/account-card.component.scss
  libs/angular-components/cards/account-card/src/account-card.component.spec.ts
  libs/angular-components/cards/account-card/src/account-card.component.ts
  libs/angular-components/cards/account-card/src/account-card.module.spec.ts
  libs/angular-components/cards/account-card/src/account-card.module.ts
  libs/angular-components/cards/account-card/src/account-card.skeleton.html
  libs/angular-components/cards/account-card/src/account.interface.ts
  libs/angular-components/cards/account-card/test-setup.ts
  libs/angular-components/cards/account-card/tsconfig.json
  libs/angular-components/cards/account-card/tsconfig.lib.json
  libs/angular-components/cards/account-card/tsconfig.spec.json
  libs/angular-components/cards/account-card/tslint.json
  nx.json
  themes/angular-theme/lib/icon/_icon-base.scss
  themes/angular-theme/lib/icon/_icon-theme.scss
  tsconfig.json
Labels: component, enhancement

#215 fix(global-nav): Display current node in navbar
  apps/angular-test-app/src/app/components/global-nav-demo/global-nav-demo.component.ts
  libs/angular-components/cards/account-card/README.md
  libs/angular-components/global-nav/src/_variables.scss
  libs/angular-components/global-nav/src/components/navbar/navbar.component.html
  libs/angular-components/global-nav/src/components/navbar/navbar.component.scss
  libs/angular-components/global-nav/src/components/navbar/navbar.component.ts
  libs/angular-components/global-nav/src/global-nav.component.html
  libs/angular-components/global-nav/src/global-nav.component.spec.ts
  libs/angular-components/global-nav/src/global-nav.component.ts
  libs/angular-components/global-nav/src/services/navigation.model.ts
Labels: bug, component

#217 fix(filter): improve filter tags
  libs/angular-components/filter/filter-tags/index.ts
  libs/angular-components/filter/filter-tags/src/_filter-tags.theme.scss
  libs/angular-components/filter/filter-tags/src/filter-tags.component.html
  libs/angular-components/filter/filter-tags/src/filter-tags.component.scss
  libs/angular-components/filter/filter-tags/src/filter-tags.component.spec.ts
  libs/angular-components/filter/filter-tags/src/filter-tags.component.ts
  libs/angular-components/filter/filter-tags/src/filter-tags.module.ts
  libs/angular-components/filter/filter-tags/src/highlight.pipe.spec.ts
  libs/angular-components/filter/filter-tags/src/highlight.pipe.ts
Labels: bug, component, enhancement

#220 bugfix(select): fix select arrow
  apps/angular-test-app/src/app/components/ui-elements-demo/ui-elements-demo.component.html
  themes/angular-theme/lib/select/_select-base.scss
Labels: bug, theme

#218 bugfix(user-profile): fix template
  libs/angular-components/user-profile-menu/src/user-profile-panel.component.html
Labels: bug, component

#219 fix mat-icons positioning in table actions
  apps/angular-test-app/src/app/components/table-demo/table-demo.component.ts
  themes/angular-theme/lib/table/_table-base.scss
Labels: bug, component
