Repository Finastra/finastra-design-system, pull requests merged in 2020-11, with the labels that each got.

#289 feat(filter-tree): configurable selection mode
  libs/angular-components/filter/filter-tree/src/filter-tree.component.ts
Labels: component, enhancement

#293 fix(filter-toggle): clear selection not emitting change
  libs/angular-components/filter/filter-toggle/src/filter-toggle.component.ts
Labels: bug, component

#297 feat(theme): add spacing helpers
  .github/workflows/pr-build.yml
  apps/angular-test-app/src/app/components/search-input-demo/search-input-demo.component.html
  apps/angular-test-app/src/app/components/skeleton-demo/skeleton-demo.component.html
  package-lock.json
  package.json
  themes/angular-theme/lib/core/style/_spacing.scss
Labels: theme

#299 feat(filter-tags): configurable placeholder
  libs/angular-components/filter/filter-tags/src/filter-tags.component.html
  libs/angular-components/filter/filter-tags/src/filter-tags.component.ts
Labels: component, enhancement
