Repository Finastra/finastra-design-system, pull requests merged in 2020-02, with the labels that each got.

#126 fix(theme): adjust button toggle height
  apps/angular-test-app/src/app/components/filter-panel-demo/filter-panel-demo.component.html
  themes/angular-theme/lib/button-toggle/_button-toggle-theme.scss
Labels: bug, theme

#130 chore(update-deps): update Angular 9 peer deps
  libs/angular-components/package.json
  themes/angular-theme/package.json
Labels: 3rd-party, bug

#134 fix(schematics): fix components generation
  tools/schematics/angular-component/files/ng-package.json.template
  tools/schematics/angular-component/files/src/__filename__.component.scss.template
Labels: bug, config

#123 feat(vector-map): changed projection type, so it better fills the uxp component
  apps/angular-test-app/src/styles.scss
  libs/angular-components/vector-map/src/_vector-map.theme.scss
  libs/angular-components/vector-map/src/vector-map.component.html
  libs/angular-components/vector-map/src/vector-map.component.scss
  libs/angular-components/vector-map/src/vector-map.models.ts
Labels: component, enhancement

#137 feat(dark-theme): persist value of dark theme
  apps/angular-test-app/src/app/app.component.html
  apps/angular-test-app/src/app/app.component.ts
Labels: demo, enhancement

#138 refactor(routing): Use only one source of truth for routes
  apps/angular-test-app/src/app/app.component.html
  apps/angular-test-app/src/app/app.component.ts
  apps/angular-test-app/src/app/components/home/home.component.html
  apps/angular-test-app/src/app/components/home/home.component.spec.ts
  apps/angular-test-app/src/app/components/home/home.component.ts
  apps/angular-test-app/src/app/nested-routes.ts
  apps/angular-test-app/src/app/routes.ts
Labels: demo, enhancement

#140 feat (table) add optional emiter to cell template table
  apps/angular-test-app/src/app/components/table-demo/table-demo.component.html
  apps/angular-test-app/src/app/components/table-demo/table-demo.component.scss
  apps/angular-test-app/src/app/components/table-demo/table-demo.component.ts
  libs/angular-components/table/src/table.component.html
  libs/angular-components/table/src/table.component.ts
  libs/angular-components/table/src/table.models.ts
  package.json
Labels: component, enhancement

#141 fix: upgrade angular 9
  angular.json
  apps/angular-test-app/src/app/components/wizard-demo/wizard-demo.component.spec.ts
  apps/angular-test-app/src/test-setup.ts
  jest.global-mocks.ts
  libs/angular-components/chart/ng-package.json
  libs/angular-components/chart/src/chart.module.ts
  libs/angular-components/index.ts
  libs/angular-components/package.json
  libs/angular-components/repeater/index.ts
  libs/angular-components/tsconfig.lib.json
  libs/angular-components/vector-map/src/vector-map.component.ts
  libs/angular-components/vector-map/src/vector-map.module.ts
  libs/angular-components/vector-map/tsconfig.spec.json
  package-lock.json
  package.json
  tools/devkit/builders/components/components-builder.ts
  tsconfig.json
  tslint.json
Labels: 3rd-party, breaking-change, config

#136 style(home): Fix padding
  apps/angular-test-app/src/app/components/home/home.component.scss
Labels: demo, enhancement

#125 fix(icon-button): fixed icon-button behaviour when clicked in IE11
  themes/angular-theme/lib/button/_button-base.scss
  themes/angular-theme/lib/icon/_icon-base.scss
Labels: bug, theme

#135 feat(skeleton-text): New component uxg-skeleton-text
  angular.json
  apps/angular-test-app/src/app/app-routing.module.ts
  apps/angular-test-app/src/app/components/home/home.component.html
  apps/angular-test-app/src/app/components/home/home.component.scss
  apps/angular-test-app/src/app/components/skeleton-demo/skeleton-demo.component.html
  apps/angular-test-app/src/app/components/skeleton-demo/skeleton-demo.component.scss
  apps/angular-test-app/src/app/components/skeleton-demo/skeleton-demo.component.spec.ts
  apps/angular-test-app/src/app/components/skeleton-demo/skeleton-demo.component.ts
  apps/angular-test-app/src/app/nested-routes.ts
  apps/angular-test-app/src/styles.scss
  libs/angular-components/skeleton-text/index.ts
  libs/angular-components/skeleton-text/jest.config.js
  libs/angular-components/skeleton-text/ng-package.json
  libs/angular-components/skeleton-text/package.json
  libs/angular-components/skeleton-text/src/_skeleton-text.theme.scss
  libs/angular-components/skeleton-text/src/skeleton-text.component.html
  libs/angular-components/skeleton-text/src/skeleton-text.component.scss
  libs/angular-components/skeleton-text/src/skeleton-text.component.spec.ts
  libs/angular-components/skeleton-text/src/skeleton-text.component.ts
  libs/angular-components/skeleton-text/src/skeleton-text.module.spec.ts
  libs/angular-components/skeleton-text/src/skeleton-text.module.ts
  libs/angular-components/skeleton-text/test-setup.ts
  libs/angular-components/skeleton-text/tsconfig.json
  libs/angular-components/skeleton-text/tsconfig.lib.json
  libs/angular-components/skeleton-text/tsconfig.spec.json
  libs/angular-components/skeleton-text/tslint.json
  nx.json
  tsconfig.json
Labels: component, demo

#144 feat(schematics): Generate mixins with "theme" suffix
  apps/angular-test-app/src/styles.scss
  libs/angular-components/skeleton-text/src/_skeleton-text.theme.scss
  tools/schematics/angular-component/files/src/__scssFilename__.theme.scss.template
Labels: component, enhancement

#132 feat(filter-tree): tab-index
  libs/angular-components/filter/filter-tree/src/filter-tree.component.html
  libs/angular-components/filter/filter-tree/src/filter-tree.component.scss
Labels: bug, component

#122 feat(wizard): add mobile layout
  apps/angular-test-app/src/styles.scss
  libs/angular-components/wizard/src/_wizard.theme.scss
  libs/angular-components/wizard/src/services/page-collection.service.ts
  libs/angular-components/wizard/src/services/wizard-navigation.service.ts
  libs/angular-components/wizard/src/wizard-button/wizard-button.component.html
  libs/angular-components/wizard/src/wizard-button/wizard-button.component.ts
  libs/angular-components/wizard/src/wizard.component.html
  libs/angular-components/wizard/src/wizard.component.scss
  libs/angular-components/wizard/src/wizard.component.spec.ts
  libs/angular-components/wizard/src/wizard.component.ts
  libs/angular-components/wizard/src/wizard.module.ts
Labels: component, enhancement

#147 fix: can not compile with ivy
  angular.json
  apps/angular-test-app/src/app/components/vector-map-demo/vector-map-demo.component.spec.ts
  apps/angular-test-app/tsconfig.app.json
  jest.global-mocks.ts
  libs/angular-components/chart/src/chart.component.spec.ts
  libs/angular-components/chart/src/chart.module.spec.ts
  libs/angular-components/chart/src/chart.module.ts
  libs/angular-components/chart/tsconfig.lib.json
  libs/angular-components/core/index.ts
  libs/angular-components/core/src/lazyload-script.ts
  libs/angular-components/vector-map/src/vector-map.module.spec.ts
  libs/angular-components/vector-map/src/vector-map.module.ts
  libs/angular-components/vector-map/tsconfig.spec.json
  package-lock.json
  package.json
Labels: bug, config

#148 fix(slide-toggle): remove primary color enforcement for slide-toggle
  themes/angular-theme/lib/core/theming/_all-theme.scss
  themes/angular-theme/lib/slide-toggle/_slide-toggle-theme.scss
Labels: bug, theme
