Repository Finastra/finastra-design-system, pull requests merged in 2020-04, with the labels that each got.

#128 feat(config): pr build with github actions
  .github/workflows/pr-build.yml
Labels: config, enhancement, work-in-progress

#176 fix(table): fix table cell align not work
  apps/angular-test-app/src/app/components/table-demo/table-demo.component.ts
  apps/angular-test-app/src/app/nested-routes.ts
  libs/angular-components/table/src/table.component.scss
Labels: bug, component

#165 feat(input): implement fill appearance for input
  angular.json
  apps/angular-test-app/src/_redirects
  apps/angular-test-app/src/app/components/filter-panel-demo/filter-panel-demo.component.scss
  apps/angular-test-app/src/app/components/ui-elements-demo/ui-elements-demo.component.html
  apps/angular-test-app/src/app/components/ui-elements-demo/ui-elements-demo.component.ts
  apps/angular-test-app/src/app/nested-routes.ts
  libs/angular-components/filter/filter-tags/src/filter-tags.component.html
  libs/angular-components/filter/filter-tags/src/filter-tags.component.scss
  package-lock.json
  package.json
  themes/angular-theme/lib/core/typography/_all-typography.scss
  themes/angular-theme/lib/form-field/_form-field-base.scss
  themes/angular-theme/lib/form-field/_form-field-theme.scss
Labels: enhancement, theme

#139 feat(filter): add multiselect tags filter
  angular.json
  apps/angular-test-app/src/app/app-routing.module.ts
  apps/angular-test-app/src/app/components/filter-panel-demo/filter-panel-demo.component.html
  apps/angular-test-app/src/app/components/filter-panel-demo/filter-panel-demo.component.ts
  apps/angular-test-app/src/styles.scss
  libs/angular-components/filter/filter-group/src/_filter-group.theme.scss
  libs/angular-components/filter/multiselect-tags/index.ts
  libs/angular-components/filter/multiselect-tags/jest.config.js
  libs/angular-components/filter/multiselect-tags/ng-package.json
  libs/angular-components/filter/multiselect-tags/package.json
  libs/angular-components/filter/multiselect-tags/src/multiselect-tags.component.html
  libs/angular-components/filter/multiselect-tags/src/multiselect-tags.component.scss
  libs/angular-components/filter/multiselect-tags/src/multiselect-tags.component.spec.ts
  libs/angular-components/filter/multiselect-tags/src/multiselect-tags.component.ts
  libs/angular-components/filter/multiselect-tags/src/multiselect-tags.module.spec.ts
  libs/angular-components/filter/multiselect-tags/src/multiselect-tags.module.ts
  libs/angular-components/filter/multiselect-tags/test-setup.ts
  libs/angular-components/filter/multiselect-tags/tsconfig.json
  libs/angular-components/filter/multiselect-tags/tsconfig.lib.json
  libs/angular-components/filter/multiselect-tags/tsconfig.spec.json
  libs/angular-components/filter/multiselect-tags/tslint.json
  nx.json
  tsconfig.json
Labels: component, enhancement

#180 chore(config): added release workflow
  .github/workflows/release.yml
Labels: config, enhancement

#181 bugfix(multiselect-filter): fix readonly property bug
  libs/angular-components/filter/multiselect-tags/src/multiselect-tags.component.ts
Labels: bug, component

#183 feat(wizard): improve wizard
  apps/angular-test-app/src/app/components/wizard-demo/wizard-demo.component.html
  apps/angular-test-app/src/styles.scss
  libs/angular-components/wizard/src/_wizard.theme.scss
  libs/angular-components/wizard/src/wizard-page/wizard-page.component.ts
  libs/angular-components/wizard/src/wizard.component.html
  libs/angular-components/wizard/src/wizard.component.scss
  libs/angular-components/wizard/src/wizard.component.ts
  package-lock.json
  package.json
  themes/angular-theme/lib/core/theming/_palette.scss
Labels: component, enhancement

#177 feat(expandable table): new expandable table component
  angular.json
  apps/angular-test-app/src/app/app-routing.module.ts
  apps/angular-test-app/src/app/components/expandable-table-demo/expandable-table-demo.component.html
  apps/angular-test-app/src/app/components/expandable-table-demo/expandable-table-demo.component.scss
  apps/angular-test-app/src/app/components/expandable-table-demo/expandable-table-demo.component.ts
  apps/angular-test-app/src/app/nested-routes.ts
  libs/angular-components/core/index.ts
  libs/angular-components/core/src/utils/create-chain.ts
  libs/angular-components/expandable-table/README.md
  libs/angular-components/expandable-table/jest.config.js
  libs/angular-components/expandable-table/src/expandable-table.component.html
  libs/angular-components/expandable-table/src/expandable-table.component.scss
  libs/angular-components/expandable-table/src/expandable-table.component.spec.ts
  libs/angular-components/expandable-table/src/expandable-table.component.ts
  libs/angular-components/expandable-table/src/expandable-table.module.ts
  libs/angular-components/expandable-table/src/index.ts
  libs/angular-components/expandable-table/src/test-setup.ts
  libs/angular-components/expandable-table/tsconfig.json
  libs/angular-components/expandable-table/tsconfig.lib.json
  libs/angular-components/expandable-table/tsconfig.lib.prod.json
  libs/angular-components/expandable-table/tsconfig.spec.json
  libs/angular-components/expandable-table/tslint.json
  libs/angular-components/table/src/table.component.html
  nx.json
  themes/angular-theme/lib/table/_table-theme.scss
  tsconfig.json
Labels: component, demo, enhancement

#184 bugfix(expandable-table): add package.json
  libs/angular-components/expandable-table/ng-package.json
  libs/angular-components/expandable-table/package.json
Labels: bug, component

#173 feat(banner): new banner component
  angular.json
  apps/angular-test-app/src/app/app-routing.module.ts
  apps/angular-test-app/src/app/components/banner-demo/banner-demo.component.html
  apps/angular-test-app/src/app/components/banner-demo/banner-demo.component.scss
  apps/angular-test-app/src/app/components/banner-demo/banner-demo.component.ts
  apps/angular-test-app/src/app/material.module.ts
  apps/angular-test-app/src/app/nested-routes.ts
  apps/angular-test-app/src/styles.scss
  libs/angular-components/banner/README.md
  libs/angular-components/banner/index.ts
  libs/angular-components/banner/jest.config.js
  libs/angular-components/banner/ng-package.json
  libs/angular-components/banner/package.json
  libs/angular-components/banner/src/_banner.theme.scss
  libs/angular-components/banner/src/banner.component.html
  libs/angular-components/banner/src/banner.component.scss
  libs/angular-components/banner/src/banner.component.spec.ts
  libs/angular-components/banner/src/banner.component.ts
  libs/angular-components/banner/src/banner.module.spec.ts
  libs/angular-components/banner/src/banner.module.ts
  libs/angular-components/banner/src/model.ts
  libs/angular-components/banner/test-setup.ts
  libs/angular-components/banner/tsconfig.json
  libs/angular-components/banner/tsconfig.lib.json
  libs/angular-components/banner/tsconfig.spec.json
  libs/angular-components/banner/tslint.json
  nx.json
  tsconfig.json
Labels: component, enhancement

#171 feat(global-nav): implem components and demo
  angular.json
  apps/angular-test-app/src/app/app-routing.module.ts
  apps/angular-test-app/src/app/components/global-nav-demo/global-nav-demo.component.html
  apps/angular-test-app/src/app/components/global-nav-demo/global-nav-demo.component.scss
  apps/angular-test-app/src/app/components/global-nav-demo/global-nav-demo.component.ts
  apps/angular-test-app/src/app/nested-routes.ts
  libs/angular-components/global-nav/README.md
  libs/angular-components/global-nav/index.ts
  libs/angular-components/global-nav/jest.config.js
  libs/angular-components/global-nav/ng-package.json
  libs/angular-components/global-nav/package.json
  libs/angular-components/global-nav/src/_global-nav.theme.scss
  libs/angular-components/global-nav/src/components/navbar/navbar.component.html
  libs/angular-components/global-nav/src/components/navbar/navbar.component.scss
  libs/angular-components/global-nav/src/components/navbar/navbar.component.ts
  libs/angular-components/global-nav/src/components/sidenav/sidenav.component.html
  libs/angular-components/global-nav/src/components/sidenav/sidenav.component.scss
  libs/angular-components/global-nav/src/components/sidenav/sidenav.component.ts
  libs/angular-components/global-nav/src/global-nav.component.html
  libs/angular-components/global-nav/src/global-nav.component.scss
  libs/angular-components/global-nav/src/global-nav.component.spec.ts
  libs/angular-components/global-nav/src/global-nav.component.ts
  libs/angular-components/global-nav/src/global-nav.module.spec.ts
  libs/angular-components/global-nav/src/global-nav.module.ts
  libs/angular-components/global-nav/src/services/navigation.model.ts
  libs/angular-components/global-nav/test-setup.ts
  libs/angular-components/global-nav/tsconfig.json
  libs/angular-components/global-nav/tsconfig.lib.json
  libs/angular-components/global-nav/tsconfig.spec.json
  libs/angular-components/global-nav/tslint.json
  nx.json
  tsconfig.json
Labels: component, e2e-tests-required, enhancement

#190 fix(project): fix github workflows affected tasks
  .github/workflows/pr-build.yml
  libs/angular-components/avatar/src/avatar.component.ts
  libs/angular-components/filter/multiselect-tags/src/multiselect-tags.component.spec.ts
  libs/angular-components/filter/multiselect-tags/src/multiselect-tags.component.ts
  libs/angular-components/user-profile-menu/src/user-profile-menu.component.spec.ts
  libs/angular-components/user-profile-menu/src/user-profile-menu.module.spec.ts
  nx.json
Labels: bug, component, config

#192 bugfix(table): fix table custom page size
  libs/angular-components/table/src/table.component.html
Labels: component

#193 fix(global-nav): fix icon name
  libs/angular-components/global-nav/src/components/sidenav/sidenav.component.ts
Labels: bug, component

#191 refactor(global-nav): Rename "url" to "path"
  apps/angular-test-app/src/app/components/global-nav-demo/global-nav-demo.component.ts
  libs/angular-components/global-nav/src/components/sidenav/sidenav.component.html
  libs/angular-components/global-nav/src/components/sidenav/sidenav.component.ts
  libs/angular-components/global-nav/src/global-nav.component.scss
  libs/angular-components/global-nav/src/services/navigation.model.ts
  libs/angular-components/ng-package.json
  libs/angular-components/package.json
Labels: component, enhancement

#195 fix(global-nav): add class uxg-nav to sidenav-container
  libs/angular-components/global-nav/src/global-nav.component.html
Labels: bug, component

#196 feat(project): add pre-commit hook to lint & format
  package-lock.json
  package.json
Labels: config, enhancement

#197 bugfix(theme): fix toggle group color in dark mode
  themes/angular-theme/lib/button-toggle/_button-toggle-theme.scss
Labels: bug, theme
