Repository Finastra/finastra-design-system, pull requests merged in 2021-02, with the labels that each got.

#256 fix(theme): make dark theme AA compliant
  apps/angular-test-app/src/app/components/ui-elements-demo/ui-elements-demo.component.html
  cypress/snapshots/foundations.spec.js/Foundations -- match icons colors.snap.png
  cypress/snapshots/ui-elements.spec.js/UI Elements -- match button FAB.snap.png
  cypress/snapshots/ui-elements.spec.js/UI Elements -- match card product dense.diff.png
  cypress/snapshots/ui-elements.spec.js/UI Elements -- match card product dense.snap.png
  cypress/snapshots/ui-elements.spec.js/UI Elements -- match card solution dense.diff.png
  cypress/snapshots/ui-elements.spec.js/UI Elements -- match card solution dense.snap.png
  cypress/snapshots/ui-elements.spec.js/UI Elements -- match card workspace dense.snap.png
  cypress/snapshots/ui-elements.spec.js/UI Elements -- match default avatar.snap.png
  cypress/snapshots/ui-elements.spec.js/UI Elements -- match letter avatar.snap.png
  cypress/snapshots/ui-elements.spec.js/UI Elements -- match list avatar.snap.png
  cypress/snapshots/ui-elements.spec.js/UI Elements -- match list dense avatar.snap.png
  cypress/snapshots/ui-elements.spec.js/UI Elements -- match toggle dense.snap.png
  cypress/snapshots/ui-elements.spec.js/UI Elements -- match toggle filter.snap.png
  cypress/snapshots/ui-elements.spec.js/UI Elements -- match toggle group.snap.png
  libs/angular-components/CHANGELOG.md
  scripts/standard-version-updater.js
  themes/angular-theme/CHANGELOG.md
  themes/angular-theme/_theme-variables.scss
  themes/angular-theme/lib/avatar/_avatar-theme.scss
  themes/angular-theme/lib/button-toggle/_button-toggle-base.scss
  themes/angular-theme/lib/button-toggle/_button-toggle-theme.scss
  themes/angular-theme/lib/card/_card-theme.scss
  themes/angular-theme/lib/chips/_chips-theme.scss
  themes/angular-theme/lib/core/theming/_palette.scss
  themes/angular-theme/lib/core/theming/_theming.scss
Labels: enhancement

#320 bugfix(filter-tags): configurable aria-label
  libs/angular-components/filter/filter-tags/src/filter-tags.component.html
  libs/angular-components/filter/filter-tags/src/filter-tags.component.ts
Labels: bug, component, enhancement

#323 [angular-components] update lodash in peerDeps for known vulnerability
  libs/angular-components/package.json
Labels: component
